server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root_pass
  jpa:
    open-in-view: false